/******************************************************************************
 * Copyright (c) 2013 ABB Group
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/legal/epl-v10.html
 *
 * Contributors:
 *    Vinay Augustine (ABB Group) - initial API, implementation, & documentation
 *****************************************************************************/

using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Xml.Linq;

namespace ABB.SrcML.Data {
    /// <summary>
    /// The data archive is an incrementally updating data container.
    /// </summary>
    /// <example>
    /// <code>
    /// var sourceFolder = new FileSystemSourceFolder("path to folder");
    /// var archive = new SrcMLArchive(sourceFolder);
    /// 
    /// // this should generate a data archive for the given srcML archive
    /// // when we start serializing data, we should consider how the location of the data can be stored in the srcmL archive
    /// // calling "DataArchive" on a srcML archive that already has data should transparently load the existing data
    /// DataArchive data = new DataArchive(archive);
    ///
    /// // testDeclaration is some declaration within archive
    /// var testDeclaration = new XElement(SRC.Declaration, "test data");
    /// 
    /// // The TypeUse object represents the context that the type is being used in
    /// TypeUse typeUseForDeclaration = new TypeUse(testDeclaration);
    /// TypeDefinition typeInfo = data.ResolveType(typeUseForDeclaration);
    /// 
    /// // one of the thing we should be able to do is get the original XML. Behind the scenes, this relies on using XPath queries
    /// // generated by Extensions.GetXPath()
    /// XElement typeXml = typeInfo.GetXElement();
    /// TypeUse parentType = typeInfo.Parents.First();
    /// XElement parentXml = data.ResolveType(parentType).GetXElement();
    /// </code>
    /// </example>
    
    public class DataArchive {
        public SrcMLArchive Archive { get; set; }

        /// <summary>
        /// Create a data archive for the given srcML archive. It will subscribe to the <see cref="SrcMLArchive.SourceFileChanged"/> event.
        /// </summary>
        /// <param name="archive">The archive to monitor for changes.</param>
        public DataArchive(SrcMLArchive archive) {
            this.Archive = archive;
            this.Archive.SourceFileChanged += Archive_SourceFileChanged;
        }

        public TypeDefinition ResolveType(XElement variableDeclarationElement) {
            //var typeUse = new TypeUse(variableDeclarationElement);
            //return ResolveType(typeUse);
            throw new NotImplementedException();
        }

        public TypeDefinition ResolveType(TypeUse typeUse) {
            throw new NotImplementedException();
        }

        void Archive_SourceFileChanged(object sender, FileEventRaisedArgs e) {
            switch(e.EventType) {
                case FileEventType.FileChanged:
                    // Treat a change source file as deleted then added
                    RespondToSourceFileDeletion(e.SourceFilePath);
                    goto case FileEventType.FileAdded;
                case FileEventType.FileAdded:
                    RespondToSourceFileAddition(e.SourceFilePath);
                    break;
                case FileEventType.FileDeleted:
                    RespondToSourceFileDeletion(e.SourceFilePath);
                    break;
                case FileEventType.FileRenamed:
                    // TODO remove the file from the data archive
                    // TODO do we need the rename case? or just handle delete + add?
                    throw new NotImplementedException();
            }
        }

        /// <summary>
        /// This function is a container function for all of the different "Load" functions
        /// It is responsible for adding data for new files. It is *not* responsible for deleting existing data (<see cref="RespondToSourceFileDeletion(string)"/>
        /// </summary>
        /// <param name="pathToNewFile">the path to the source file that changed</param>
        private void RespondToSourceFileAddition(string pathToNewFile) {
            var updatedFileUnit = Archive.GetXElementForSourceFile(pathToNewFile);

            LoadTypesFromFile(updatedFileUnit);
        }

        /// <summary>
        /// This function is a container function for all of the different "Remove" functions
        /// It is responsible for removing existing data for changed or deleted files.
        /// </summary>
        /// <param name="pathToDeletedFile"></param>
        private void RespondToSourceFileDeletion(string pathToDeletedFile) {
            RemoveTypesForFile(pathToDeletedFile);
        }

        #region Type Inventory
        /// <summary>
        /// Load types from the given source file and add them to the type inventory
        /// </summary>
        /// <param name="updatedFileUnit">The file unit to get types for</param>
        private void LoadTypesFromFile(XElement updatedFileUnit) {
            throw new NotImplementedException();
        }

        private void RemoveTypesForFile(string pathToSourceFile) {
            // TODO find all types defined in the given source file and remove them
            throw new NotImplementedException();
        }
        #endregion
        
        

    }
}
