/*****************************************************************************
* This file is generated by MSBuild.
*
* DO NOT EDIT IT BY HAND and DO NOT CHECK IN CHANGES TO IT
*
*****************************************************************************/

/******************************************************************************
* Copyright (c) 2013 ABB Group
* All rights reserved. This program and the accompanying materials
* are made available under the terms of the Eclipse Public License v1.0
* which accompanies this distribution, and is available at
* http://www.eclipse.org/legal/epl-v10.html
*
* Contributors:
*    Vinay Augustine (ABB Group) - initial API, implementation, & documentation
*****************************************************************************/

using namespace System::Reflection;
using namespace System::Resources;

// Version information for an assembly consists of the following four values:
//
//      Major Version
//      Minor Version 
//      Revision
//      Build Number

[assembly:AssemblyCompanyAttribute(L"ABB")];
[assembly:NeutralResourcesLanguageAttribute(L"en-US")];
[assembly:AssemblyVersionAttribute(L"99.99.0.0")];

#if DEBUG
[assembly:AssemblyConfigurationAttribute(L"Debug")];
[assembly:AssemblyInformationalVersionAttribute(L"99.99.0.0-Debug-dev")];
#else
[assembly:AssemblyConfigurationAttribute(L"Release")];
[assembly:AssemblyInformationalVersionAttribute(L"99.99.0.0-Release-dev")];
#endif
