//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Reflection;
using System.Resources;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

[assembly: AssemblyCompany("ABB")]
[assembly: AssemblyConfiguration("Debug")]
[assembly: AssemblyVersion("2.0.48.0")]
[assembly: AssemblyFileVersion("2.0.48.0")]
[assembly: NeutralResourcesLanguage("en-US")]


