<?xml version="1.0" encoding="utf-8"?>
<!--/**************************************************************************
 * Copyright (c) 2011 ABB Group
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/legal/epl-v10.html
 *
 * Contributors:
 *    Vinay Augustine (ABB Group) - initial API, implementation, & documentation
 ***************************************************************************-->
<Database Class="SrcMLDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Table Name="" Member="Definitions">
    <Type Name="Definition">
      <Column Name="Id" Modifier="Virtual" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="FileName" Type="System.String" DbType="NVARCHAR(MAX)" CanBeNull="false" />
      <Column Name="LineNumber" Type="System.Int32" CanBeNull="false" />
      <Column Name="DefinitionTypeId" Storage="_ElementName" Type="DefinitionType" DbType="int NOT NULL" CanBeNull="false" IsDiscriminator="true" />
      <Column Name="XPath" Type="System.String" DbType="NVARCHAR(MAX)" CanBeNull="false" />
      <Column Name="Xml" Type="System.Xml.Linq.XElement" DbType="XML" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="ArchiveId" Type="System.Int32" CanBeNull="false" />
      <Column Name="ElementXName" Type="System.String" DbType="NVARCHAR(MAX)" CanBeNull="false" />
      <Association Name="Definition_ValidScope" Member="ValidScopes" ThisKey="Id" OtherKey="DefinitionId" Type="ValidScope" />
      <Association Name="Definition_MethodCall" Member="CallsFromMethod" ThisKey="Id" OtherKey="CallerId" Type="MethodCall" />
      <Association Name="Definition_MethodCall1" Member="CallsToMethod" ThisKey="Id" OtherKey="CalleeId" Type="MethodCall" />
      <Association Name="Archive_Definition" Member="Archive" ThisKey="ArchiveId" OtherKey="Id" Type="Archive" IsForeignKey="true" />
      <Type Name="UnknownDefinition" InheritanceCode="0" IsInheritanceDefault="true" />
      <Type Name="Declaration" Modifier="Abstract">
        <Column Name="VariableName" Member="DeclarationName" Storage="_VariableNameElement" Type="System.String" DbType="NVARCHAR(1024)" CanBeNull="true" />
        <Column Name="IsGlobal" Type="System.Boolean" CanBeNull="true" />
        <Type Name="VariableDeclaration" InheritanceCode="5">
          <Column Name="VariableTypeName" Type="System.String" DbType="NVARCHAR(1024)" CanBeNull="true" />
        </Type>
        <Type Name="MethodDeclaration" InheritanceCode="6">
          <Column Name="DeclarationClassName" Type="System.String" DbType="NVARCHAR(1024)" CanBeNull="true" />
          <Column Name="DeclarationReturnTypeName" Type="System.String" DbType="NVARCHAR(1024)" CanBeNull="true" />
          <Column Name="DeclarationNumberOfParameters" Type="System.Int32" CanBeNull="true" />
          <Column Name="DeclarationNumberOfParametersWithDefaults" Type="System.Int32" CanBeNull="true" />
        </Type>
        <Type Name="TypeDeclaration" InheritanceCode="7" />
      </Type>
      <Type Name="ScopeDefinition" InheritanceCode="1">
        <Type Name="TypeDefinition" InheritanceCode="3">
          <Column Name="TypeName" Storage="_TypeNameElement" Type="System.String" DbType="NVARCHAR(1024)" CanBeNull="true" />
        </Type>
        <Type Name="MethodDefinition" InheritanceCode="4">
          <Column Name="MethodName" Storage="_MethodNameElement" Type="System.String" DbType="NVARCHAR(1024)" CanBeNull="true" />
          <Column Name="MethodClassName" Storage="_MethodClassNameElement" Type="System.String" DbType="NVARCHAR(1024)" CanBeNull="true" />
          <Column Name="MethodReturnTypeName" Type="System.String" DbType="NVARCHAR(1024)" CanBeNull="true" />
          <Column Name="NumberOfMethodParameters" Type="System.Int32" CanBeNull="true" />
          <Column Name="NumberOfMethodParametersWithDefaults" Type="System.Int32" CanBeNull="true" />
          <Column Name="MethodSignature" Type="System.String" DbType="NVARCHAR(MAX)" CanBeNull="true" />
        </Type>
      </Type>
    </Type>
  </Table>
  <Table Name="" Member="Archives">
    <Type Name="Archive">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Path" Type="System.String" DbType="NVARCHAR(MAX)" CanBeNull="false" />
      <Column Name="LastUpdated" Type="System.DateTime" CanBeNull="false" />
      <Association Name="Archive_Definition" Member="Definitions" ThisKey="Id" OtherKey="ArchiveId" Type="Definition" />
    </Type>
  </Table>
  <Table Name="" Member="ValidScopes">
    <Type Name="ValidScope">
      <Column Name="Id" AutoSync="OnInsert" Type="System.Int32" DbType="int NOT NULL IDENTITY" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="DefinitionId" Type="System.Int32" CanBeNull="false" />
      <Column Name="XPath" Type="System.String" DbType="NVARCHAR(MAX)" CanBeNull="false" />
      <Association Name="Definition_ValidScope" Member="Definition" ThisKey="DefinitionId" OtherKey="Id" Type="Definition" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="" Member="MethodCalls">
    <Type Name="MethodCall">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="CallerId" Type="System.Int32" CanBeNull="false" />
      <Column Name="CalleeId" Type="System.Int32" CanBeNull="false" />
      <Column Name="XPath" Type="System.String" CanBeNull="false" />
      <Column Name="LineNumber" Type="System.Int32" CanBeNull="false" />
      <Association Name="Definition_MethodCall" Member="CallerDefinition" ThisKey="CallerId" OtherKey="Id" Type="Definition" IsForeignKey="true" />
      <Association Name="Definition_MethodCall1" Member="CalleeDefinition" ThisKey="CalleeId" OtherKey="Id" Type="Definition" IsForeignKey="true" />
    </Type>
  </Table>
</Database>